<?php
/*
* Plugin Name : MyPlugin
*/

namespace Plugin\MyPlugin\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\MyPlugin\Entity\MyPluginConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * MyPlugin Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyPluginConfigRepository extends AbstractRepository
{
    /**
     * MyPluginConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, MyPluginConfig::class);
    }

    /**
     * @param int $id
     *
     * @return null|MyPluginConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}